# Generated by Django 2.0.7 on 2019-05-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='codigo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
