# Generated by Django 2.0.7 on 2019-05-15 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190515_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmprestarLivro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculaLivro', models.CharField(max_length=15)),
                ('alugado', models.BooleanField(default=False)),
                ('codigoLivro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Livro')),
            ],
        ),
    ]
